export const SIGNUPUSER = 'SIGNUPUSER'
export const SIGNIN = 'SIGNIN'
export const GET_ERROR = 'GET_ERROR'
export const LOADING = 'LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const GOOGLE_PLACES_AUTOCOMPLETE = 'GOOGLE_PLACES_AUTOCOMPLETE'
export const LOGOUT = 'LOGOUT'
export const FETCH_BUS = 'FETCH_BUS'
export const ADD_BUS_LOCATION = 'ADD_BUS_LOCATION'
export const GET_BUS_LOCATION = 'GET_BUS_LOCATION'
export const GET_BUS_ON_SELECTED_ROUTE = 'GET_BUS_ON_SELECTED_ROUTE'
export const GET_PASSENGER = 'GET_PASSENGER'
export const GET_WAITING_FOR = 'GET_WAITING_FOR'




// new

export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_ROUTE = 'SET_ROUTE'
export const SELECT_ROUTE = 'SELECT_ROUTE'
export const UPDATE_BUS_LOCATION = 'UPDATE_BUS_LOCATION'
export const PASSENGER_LOCATION = 'PASSENGER_LOCATION'
export const PASSENER_LOGIN = 'PASSENGER_LOGIN'
export const SELECT_BUS = 'SELECT_BUS'